version: '3'

services:
  jekyll:
    image: ruby:3.2-slim
    container_name: modern-resume-theme
    command: >
      bash -c "apt-get update && 
               apt-get install -y git build-essential && 
               git config --global --add safe.directory /site && 
               gem install bundler:2.1.4 && 
               bundle install && 
               bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling --verbose"
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/site
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    working_dir: /site
